## Stage 1: Builder
FROM kalilinux/kali-rolling AS kali

ENV DEBIAN_FRONTEND=noninteractive

# Set working directory
WORKDIR /app

RUN \
  sed -i "s@http://http.kali.org/kali@http://mirrors.tuna.tsinghua.edu.cn/kali@g" /etc/apt/sources.list && \
  dpkg --add-architecture i386 && \
  apt-get -y update && apt-get -y upgrade && \
  apt-get -y install libc6:i386 && \
  apt-get -y install python3 python3-pip python3-dev python-is-python3 \
    python3-requests python3-requests-futures python3-bs4 python3-pwntools \
    python3-ropgadget python3-binwalk python3-fpylll \
    python3-aiohttp python3-coverage python3-pycryptodome python3-pyqtgraph \
    python3-qrcode python3-pyshark python3-regex \
    python3-numpy python3-scipy python3-matplotlib python3-pandas \
    python3-sympy python3-gmpy2 python3-z3 \
    python3-capstone python3-cstruct python3-loguru \
    python3-tk python3-filetype python3-ciphey python3-scapy \
    python3-opencv python3-psycopg \
    python3-geoip2 python3-cartopy python3-pyx python3-graphviz && \
  apt-get -y install curl wget git \
    build-essential binutils-x86-64-linux-gnu elfutils patchelf debuginfod \
    unblob binwalk libimage-exiftool-perl hydra tshark gdb-multiarch \
    checksec steghide beef-xss sqlmap dirsearch &&\
  apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

    # sagemath uncompyle pycdc volatility3
