[project]
name = "mcp-code-runner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "docker>=7.1.0",
    "fastmcp>=2.11.3",
    "paramiko>=4.0.0",
]
